/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_devtech_filepipeline_impl_util_ZipFileSystemInternal */

#ifndef _Included_net_devtech_filepipeline_impl_util_ZipFileSystemInternal
#define _Included_net_devtech_filepipeline_impl_util_ZipFileSystemInternal
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_devtech_filepipeline_impl_util_ZipFileSystemInternal
 * Method:    sync0
 * Signature: (Ljava/nio/file/FileSystem;)V
 */
JNIEXPORT void JNICALL Java_net_devtech_filepipeline_impl_util_ZipFileSystemInternal_sync0
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
