/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_devtech_filepipeline_impl_util_flushzipfs_NativeZipFsFlush */

#ifndef _Included_net_devtech_filepipeline_impl_util_flushzipfs_NativeZipFsFlush
#define _Included_net_devtech_filepipeline_impl_util_flushzipfs_NativeZipFsFlush
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_devtech_filepipeline_impl_util_flushzipfs_NativeZipFsFlush
 * Method:    flushZipFs
 * Signature: (Ljava/nio/file/FileSystem;)V
 */
JNIEXPORT void JNICALL Java_net_devtech_filepipeline_impl_util_flushzipfs_NativeZipFsFlush_flushZipFs
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
