name: Natives
on: [ workflow_dispatch ] # Manual trigger

permissions:
  contents: write

# I use windows and am just using gh actions to compile for linux and macos
jobs:
  natives_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 18
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - run: chmod +x gradlew
      - run: ./gradlew native_X64SharedLibrary --no-daemon
      - uses: actions/upload-artifact@v2
        with:
          name: native-linux-x64
          path: build/libs/native_/shared/x64/libnative_.so
  natives_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 18
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - run: gradle native_X64SharedLibrary --no-daemon
      - uses: actions/upload-artifact@v2
        with:
          name: native-macos-x64
          path: build/libs/native_/shared/x64/libnative_.dylib