name: Publish
on: [ workflow_dispatch ] # Manual trigger

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 18
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - run: chmod +x gradlew
      - run: ./gradlew native_X64SharedLibrary --no-daemon
      - uses: actions/upload-artifact@v2
        with:
          name: native-linux-x64
          path: $GITHUB_WORKSPACE/build/libs/native_/64/native_.so