name: Publish
on: [workflow_dispatch] # Manual trigger

permissions:
  contents: write

jobs:
  buildLinux:
    runs-on: ubuntu-20.04
    container:
      image: eclipse-temurin:18-jdk
      options: --user root
    steps:
      - uses: actions/checkout@v3
      - name: Set up MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64
    - uses: gradle/wrapper-validation-action@v1
    - run: ./gradlew native_X64SharedLibrary --no-daemon
    - uses: actions/upload-artifact@v2
      with:
        name: native-linux-x64
        path: $GITHUB_WORKSPACE/build/libs/native_/64/native_.so